---
title: "Draft Quarto document"
author: "Naja"
format: html
editor_options: 
  chunk_output_type: console
---

## Header 1

```{r setup}
#| include: false
library(tidyverse)
library(here)
library(snakecase)
library(lubridate)
library(fs)
library(stringr)
source(here("R/functions.R"))
cgm_data <- here("data-raw/dime/cgm") |> 
  import_csv_files() |> 
  get_participant_id() |>
  prepare_dates(device_timestamp)
# Sleep data
sleep_data <- here("data-raw/dime/sleep") |>
  import_csv_files() |>
  get_participant_id() |>
  rename(datetime = date) |>
  prepare_dates(datetime)
```

```{r}
# Code chunk
```

## Importing CGM data. 
```{r}
cgm_101 <- here("data-raw/dime/cgm/101.csv") %>%
  read_csv(
    show_col_types = FALSE,
    name_repair = to_snake_case,
    n_max = 100
  )
```

## Importing Sleep data on cgm_101 patient

```{r}
sleep_101 <- here("data-raw/dime/sleep/101.csv") |>
  read_csv(
    show_col_types = FALSE,
    name_repair = to_snake_case,
    n_max = 100
  )
sleep_101
```

## Making a function that adds numbers

```{r}
#' Add two numbers together
#'
#' @param num1 A number
#' @param num2 A number
#'
#' @returns Returns the sum of the numbers
#'
add_numbers <- function(num1, num2) {
  added <- num1 + num2
  return(added)
}

add_numbers(1, 2)
```


## Import 101's CMG data with a function

```{r}
#' Import on participants cgm
#'
#' @param file_path path to file you want to open
#'
#' @returns Returns a data frame
#'
import_cgm <- function(file_path) {
  cgm <- file_path %>%
    readr::read_csv(
      show_col_types = FALSE,
      name_repair = snakecase::to_snake_case,
      n_max = 100
    )
  return(cgm)
}

here("data-raw/dime/cgm/101.csv") %>%
  import_cgm()
here("data-raw/dime/cgm/102.csv") %>%
  import_cgm()
```

## Exercise: import 101's sleep data

```{r}
import_sleep <- function(file_path) {
  sleep <- file_path %>%
    read_csv(
      show_col_types = FALSE,
      name_repair = to_snake_case,
      n_max = 100
    )
  return(sleep)
}

here("data-raw/dime/sleep/101.csv") %>%
  import_sleep()
```

## Import DIME data function
```{r}
```
## checking that it works
```{r}
here("data-raw/dime/cgm/101.csv") %>%
  import_dime()

here("data-raw/dime/sleep/101.csv") %>%
  import_dime()
```


## Using map
```{r}
cgm_files <- here("data-raw/dime/cgm/") %>%
  dir_ls(glob = "*.csv")

cgm_files
```

## Exercise: Convert map to function and use on sleep.

```{r}
here("data-raw/dime/cgm/") |>
  import_csv_files()
here("data-raw/dime/sleep/") |>
  import_csv_files()
```

## Using regex for ID extraction den puttede vi så i functions

## Working with dates


```{r}
```

```{r}
```
